### PR TITLE
Assignment Done by Olivia Oputa

### PR DESCRIPTION
**Pull request by oputaolivia**
- Completed the missing routes/ logic

### CODE REVIEW

**Review by biggaji — CHANGES_REQUESTED** [review]
Welldone @oputaolivia , I really love what you've done here.
One thing though, please instead of returning an alternate response object within an else statement, please throw an error according to the instructions, the error handler will catch it and return the response.

**Comment by oputaolivia** [comment]
Noted 
Thank you

**Comment by biggaji** [comment]
> Noted Thank you

You're welcome @oputaolivia 
I'm eagerly looking forward to merge your changes.

**Comment by oputaolivia** [comment]
https://github.com/biggaji/backend-yip/commit/8f6f0d4d3d464f479f60af6e0e17b513f14d6f84
edits made here.

**Review by biggaji — APPROVED** [review]
Looks good @oputaolivia

**Pull request merged**
